### ISSUE TITLE
Modify Upload Requirements UI

### ISSUE THREAD

**Issue by AndreaTatoy** [SoftEng1-OJT-App/OJT-APP#22]

**Comment by TrixiePicana** [comment]
Component(s) added: 

- Dropdown menu (located beside the field "Status" where code adjustments were made in JavaScript Code) 
- Background color (CSS component)
- Background image behind the upload section

The image below is the updated UI of the Upload requirements page:
![image](https://github.com/user-attachments/assets/6c0b3978-4a54-4af3-9fcc-6c6a99640880)
